zuul:
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  lostAndFoundService: 
    path: /lostAndFound/**
    serviceId: lost-and-found-service
  propets-auth-service: 
    path: /auth/**
    serviceId: propets-auth-service
  ui:
    path: /**
    url: http://localhost:3000




   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: ${DOMAIN_NAME:localhost}