zuul:
 routes:
  lostAndFoundService: 
    path: /lostAndFound/**
    serviceId: lostAndFoundService
  propets-authentification-service: 
    path: /api/auth/**
    serviceId: propets-authentification-service



   
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:localhost}/eureka/
  instance:
      instanceId: ${DOMAIN_NAME}
#security:
# user:
#    password: ${eureka.password}

#---
#spring:
#  profiles: heroku
#eureka:
#  instance:
#    hostname: ${DOMAIN_NAME}
#    nonSecurePort: 80
#  password: ${USER_PASSWORD:password}