zuul:
 sensitiveHeaders: Cookie,Set-Cookie
 routes:
  lostAndFoundService: 
    path: /lostAndFound/**
    serviceId: lostAndFoundService
  propets-auth-service: 
    path: /auth/**
    serviceId: propets-auth-service
  ui:
    path: /ui/**
    url: http://84.94.104.241:3001




   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000}/eureka
  
  instance:
      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
      hostname: ${DOMAIN_NAME}
      nonSecurePort: 80