zuul:
 routes:
  lostAndFoundService: 
    path: /lostAndFound/**
    serviceId: lostAndFoundService
  propets-auth-service: 
    path: /auth/**
    serviceId: propets-auth-service
 sensitiveHeaders: Cookie,Set-Cookie



   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:5000}/eureka
  
#  instance:
#      instanceId: ${DOMAIN_NAME:localhost}:${random.value}
#      hostname: ${DOMAIN_NAME}
#      nonSecurePort: 80